#!/usr/bin/env bash
# proc-macro-guard.sh — PR 24.7 workspace-shape gate. walrus authors no procedural macros: every
# codegen need is met by `macro_rules!` (crates/common/src/string_enum.rs, and the hand-written
# transparent-int8 sqlx blocks in ids.rs / lsn.rs). Rationale + the one condition that reopens the
# decision: docs/implementation/notes/rust-skills/macro-proc-syn-quote.md.
#
#   bash scripts/proc-macro-guard.sh --check
#   bash scripts/proc-macro-guard.sh --self-test
#
# Checks MANIFESTS, never Cargo.lock — transitive proc-macros (serde_derive, thiserror-impl,
# sqlx-macros, async-trait, …) are required and must keep resolving.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

MANIFESTS=(Cargo.toml crates/*/Cargo.toml tests/e2e/Cargo.toml)

check_direct() {
  local direct
  # grep exits 1 when it matches nothing, which is the success case. Keep that status from
  # terminating a clean check under `set -e`, then decide from the captured diagnostics.
  direct=$(grep -nEH -- \
    '^[[:space:]]*(syn|quote|proc-macro2)[[:space:]]*[.=]|^[[:space:]]*\[[^]]*dependencies\.(syn|quote|proc-macro2)\]' \
    "$@" || true)

  if [ -n "$direct" ]; then
    echo "::error::direct syn/quote/proc-macro2 dependency declared in a workspace manifest — walrus authors no proc-macros (docs/implementation/notes/rust-skills/macro-proc-syn-quote.md)"
    echo "$direct"
    return 1
  fi

  echo "ok: 0 direct syn/quote/proc-macro2 dependencies across $# manifests (transitive copies are expected and fine)"
}

EXPECTED_MEMBERS=6

# PR 24.8 tests-first seams. The negative controls below land before these checks are implemented,
# so both stubs deliberately accept their bad fixtures in the intended-red commit.
check_proc_macro_setting() {
  return 0
}

check_workspace_member_count() {
  return 0
}

self_test() {
  local output new_controls_failed=0
  PROC_MACRO_GUARD_FIXTURE_DIR=$(mktemp -d)
  trap 'rm -rf -- "$PROC_MACRO_GUARD_FIXTURE_DIR"' EXIT

  mkdir -p "$PROC_MACRO_GUARD_FIXTURE_DIR/fixture"
  printf '%s\n' '[dependencies]' 'syn = "2"' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/direct-syn.toml"
  printf '%s\n' '[dependencies]' 'syn.workspace = true' 'quote.workspace = true' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/workspace-dependencies.toml"
  printf '%s\n' '[build-dependencies]' 'syn = { version = "2" }' \
    'proc-macro2 = { version = "1" }' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/inline-dependencies.toml"
  printf '%s\n' '[dev-dependencies.proc-macro2]' 'version = "1"' \
    '[build-dependencies.quote]' 'version = "1"' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/dependency-tables.toml"
  printf '%s\n' '[lib]' '  proc-macro=true' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/proc-macro.toml"

  mkdir -p "$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace"
  printf '%s\n' '[workspace]' 'resolver = "3"' \
    'members = ["member-1", "member-2", "member-3", "member-4", "member-5", "member-6", "member-7"]' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/Cargo.toml"
  printf '%s\n' '# This file is automatically @generated by Cargo.' \
    '# It is not intended for manual editing.' 'version = 4' \
    >"$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/Cargo.lock"
  for member_no in 1 2 3 4 5 6 7; do
    mkdir -p "$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/member-$member_no/src"
    printf '%s\n' '[package]' "name = \"fixture-member-$member_no\"" \
      'version = "0.1.0"' 'edition = "2024"' \
      >"$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/member-$member_no/Cargo.toml"
    printf '%s\n' '#![allow(dead_code)]' \
      >"$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/member-$member_no/src/lib.rs"
    printf '\n%s\n' '[[package]]' "name = \"fixture-member-$member_no\"" \
      'version = "0.1.0"' \
      >>"$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace/Cargo.lock"
  done

  if output=$(check_direct "$PROC_MACRO_GUARD_FIXTURE_DIR"/fixture/*.toml 2>&1); then
    echo "::error::proc-macro guard self-test expected direct dependency fixtures to be rejected"
    echo "$output"
    exit 1
  fi

  echo "$output"
  for expected in \
    '::error::direct syn/quote/proc-macro2 dependency declared' \
    'fixture/direct-syn.toml' \
    'fixture/workspace-dependencies.toml' \
    'fixture/inline-dependencies.toml' \
    'fixture/dependency-tables.toml' \
    'syn = "2"' \
    'syn.workspace = true' \
    'quote.workspace = true' \
    'syn = { version = "2" }' \
    'proc-macro2 = { version = "1" }' \
    '[dev-dependencies.proc-macro2]' \
    '[build-dependencies.quote]'; do
    if ! grep -Fq -- "$expected" <<<"$output"; then
      echo "::error::proc-macro guard self-test did not report expected fixture declaration: $expected"
      exit 1
    fi
  done

  if output=$(check_proc_macro_setting \
    "$PROC_MACRO_GUARD_FIXTURE_DIR/fixture/proc-macro.toml" 2>&1); then
    echo "::error::proc-macro guard self-test expected the proc-macro manifest fixture to be rejected"
    echo "$output"
    new_controls_failed=1
  else
    echo "$output"
    for expected in \
      '::error::a workspace manifest declares a proc-macro library setting' \
      'fixture/proc-macro.toml' \
      'proc-macro=true'; do
      if ! grep -Fq -- "$expected" <<<"$output"; then
        echo "::error::proc-macro guard self-test did not report expected proc-macro fixture detail: $expected"
        exit 1
      fi
    done
  fi

  if output=$(check_workspace_member_count \
    "$PROC_MACRO_GUARD_FIXTURE_DIR/seven-member-workspace" 2>&1); then
    echo "::error::proc-macro guard self-test expected the seven-member workspace to be rejected"
    echo "$output"
    new_controls_failed=1
  else
    echo "$output"
    for expected in \
      '::error::workspace member count is 7, expected 6' \
      'if deliberate, update the guard and two-crate decision together'; do
      if ! grep -Fq -- "$expected" <<<"$output"; then
        echo "::error::proc-macro guard self-test did not report expected member-count detail: $expected"
        exit 1
      fi
    done
  fi

  if [ "$new_controls_failed" -ne 0 ]; then
    exit 1
  fi

  echo "proc-macro-guard self-test: PASS"
}

usage() {
  echo "usage: bash scripts/proc-macro-guard.sh --check|--self-test" >&2
  exit 2
}

case "${1:-}" in
  --check)
    [ "$#" -eq 1 ] || usage
    check_direct "${MANIFESTS[@]}"
    ;;
  --self-test)
    [ "$#" -eq 1 ] || usage
    self_test
    ;;
  *)
    usage
    ;;
esac
